name: "Build a p2 repo"
description: "Builds a DBeaver-style p2 repo"

inputs:
  repo-root-dir:
    description: "The path to the root directory of the git repo with the p2 repo"

runs:
  using: composite
  steps:
    - name: Verify target-bundles
      shell: sh
      run: mvn clean verify -B -T1C
      working-directory: ${{ inputs.repo-root-dir || '.' }}

    - name: Verify P2
      shell: sh
      run: mvn clean verify -B -T1C
      working-directory: ${{ inputs.repo-root-dir || '.' }}/p2
